LOCAL:
  dynamicGPU: True # If true, presumes single GPU available and auto detects in code. False uses ID below.
  gpuNum: 0
  datasetPathsFile: "source/datasets/pathconfs/localPaths.yaml"
  # classStatsFile: "PASTISFullClassStats.csv" # unused option to expose class proportion data from pixelPopulationCounter.py for loss weighting
  saveModel: True
  saveMIoUThresh: 0.55
  modelName: "PASTIS24UTAESizeTestingAllFolds1"
  resultsDir: "/scratch/s.2275333/Results/TempSeg"
  seed: 1 # None or int default 1; 1, 2, 3 for main repeat tris

MODEL:
  architecture:  "UTAE"
  dates: "paired" # "spectralChannel", "paired" - options to switch between different model implementations
  dateOrder: "DSDS" # DSDS, DOY
  tempEmbeddingLength: 407.0 # Float with .0, what scale temporal positions will be mapped to in embedding, DOY = Ignored (365), DSDS PASTIS = 407, DSDS MTLCC = 342
  imgSize: 24 # Only square images for now
  imgSpectralChannels: 10
  maxTemporalBands: 61
  classCount: 20
  classNames: ["Background", "Meadow", "Soft Winter Wheat", "Corn", "Winter Barley", "Winter Rapeseed", "Spring Barley", "Sunflower", "Grapevine", "Beet", "Winter Triticale", "Winter Durum Wheat", "Fruits, Vegtables, & Flowers", "Potatoes", "Leguminous Fodder", "Soybeans", "Orchard", "Mixed Cereal", "Sorghum", "Void Parcel"]
  dropout: 0.1
  input_dim: 10
  encoder_widths: [64, 64, 64, 128]
  decoder_widths: [32, 32, 64, 128]
  out_conv: [32, 20]
  str_conv_k: 4
  str_conv_s: 2
  str_conv_p: 1
  agg_mode: "att_group"
  encoder_norm: "group"
  n_head: 16
  d_model: 256
  d_k: 4
  encoder: False
  return_maps: False
  pad_value: 0
  padding_mode: "reflect"
  maskBackground: False # True converts all class 19 to class 0 and masks class 0 in loss and 0, 19 in metrics, False masks class 19 in loss and metrics

RUNTIME:
  epochs: 150 # 150
  earlyStopMinEpochs: 150 # set to >= n epochs to disable early stopping (i.e. final results runs to ensure all good epochs get chance)
  earlyStopPatience: 20
  earlyStopMargin: 0.005
  lr: 0.0005 # 0.0005
  weightDecay: 0.0001 # 0.0001
  lrMinDivisor: 200
  warmupEpochs: 10

DATA:
  dataset: "PASTIS24" # PASTIS, PASTIS24, MTLCC48, MTLCC24
  folds: 1
  splits: ["PASTIS24Fold1"]
  # splits: ["PASTIS24Fold1", "PASTIS24Fold2", "PASTIS24Fold3", "PASTIS24Fold4", "PASTIS24Fold5"]
  batchSize: 4 # 4 works with all model-dataset-tilesize combos
  numWorkers: 4